build:
  services:
    mongo: 4

  environment:
    node: 12
    variables:
      NODE_ENV: 'test'
      DB_NAME: 'test'
      JWT_SECRET: '6d0d87cdac08aa35c5885702c4ddf190'
      JWT_ISSUER: 'cake.faxity.se'
      JWT_EXPIRES_IN: '15m'
      JWT_MAX_AGE: '1d'

  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
    coverage:
      tests:
        override:
          - command: yarn test
            coverage:
              file: coverage/clover.xml
              format: clover

filter:
  paths:
    - bin/
    - db/
    - lib/
    - routes/
