language: node_js
node_js: 12
services: mongodb
cache:
  yarn: true
env:
  global:
    - NODE_ENV='test'
    - DB_NAME='test'
    - JWT_SECRET='6d0d87cdac08aa35c5885702c4ddf190'
    - JWT_ISSUER='cake.faxity.se'
    - JWT_EXPIRES_IN='15m'
    - JWT_MAX_AGE='1d'
